# Android Gradle Plugin settings
android.overridePathCheck=true
android.useAndroidX=true
android.nonTransitiveRClass=true

# Gradle performance and encoding settings
org.gradle.java.home=C:\\Users\\ahmet\\.jdks\\jdk-17.0.20.1+1
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
kotlin.daemon.jvmargs=-Xmx1024m -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
